#!/bin/sh
if [ "${MOCK_MISSING:-0}" = 1 ]; then exit 127; fi
case "$1 $2" in
    '--version ')
        printf 'TShark %s\n' "${MOCK_VERSION:-1.0}"
        ;;
    '-G fields')
        case "${MOCK_FIELDS:-ok}" in
            fail) exit 1 ;;
            empty) exit 0 ;;
        esac
        printf 'F\tSource\tip.src\nF\tDestination\tip.dst\nF\tPort\ttcp.port\n'
        ;;
    '-G ')
        printf '  -G fields    Field list\n  -G protocols    Protocol list\n' >&2
        ;;
    '-F ')
        printf '  pcapng - Wireshark Next Generation\n  pcap - Libpcap\n' >&2
        ;;
    '-T __invalid__')
        printf '  "fields" Field values.\n  "json" JSON values.\n' >&2
        exit 1
        ;;
    *) exit 1 ;;
esac
